### ISSUE TITLE
Create spec for killcord interfaces

### ISSUE THREAD

**Issue by n2p5** [nomasters/killcord#2]
Until recently, the core abstractions were still being teased out, but the current struct and method system is a bit brittle. Develop interfaces specs for storage, contract, payload, and publisher to make it easier to mock these interfaces for testing and to allow a more pluggable storage and contract backend as storage and smart contract options mature over time.

**Comment by rjrbt** [comment]
Idea for simple encrypt and decrypt interfaces.

```
// The Encryptor interface expresses two methods. Encrypt, expects an io.Reader and writes to an
// io.Writer. This uses the key and chunk size for use with SecretBox, or other authenticated 
// chunk protocols. It returns an int64 of the bytes written or error.
// EncryptArchive is used to process a directory of files that first need to be archived to a single file
// and then are written to an io.Writer. This is an archive and compression wrapper for Encrypt.
type Encryptor interface {
        Encrypt(output io.Writer, input io.Reader, key [32]byte, chunkSize []byte) (written int64, error)
        EncryptArchive(dir string, io.Writer, key [32]byte,  chunk []byte) (written int64, error)
}

// The Decrypter interface expresses two methods. Decrypt, expects an io.Reader and writes to an
// io.Writer. This uses the key and chunk size for use with SecretBox, or other authenticated 
// chunk protocols. It returns an int64 of the bytes written or error.
// DecryptArchive is used to process a source from io.Reader and write to a directory. This is an archive and compression wrapper for Decrypt.
type Decryptor interface {
        Decrypt(output io.Writer, input io.Reader, key [32]byte, chunk []byte) (written int64, error)
        DecryptArchive(dir string, input io.Reader, key [32]byte, chunk []byte) (written int64, error)
}
```

**Comment by n2p5** [comment]
ideas after discussion with a friend:
- Payload should be a simple struct with a set of Methods attached to it. there isn't really in current value in adding an interface to the payload methods at this time, tools like encryption/decryption and writing to disk can all be a handled under the hood
- Storage should get an interface. `ipfsProvider` should become a struct that meets the criteria of a storage interface.
- contract should get an interface. `ethereumProvider` should become a struct that meets the criteria of a contract interface.
- publisher should be a struct with methods, not an interface
- watcher should be a struct with methods, not an interface

overall refactoring efforts should be made to ensure that methods and functions should be clean and simple to test.
