### ISSUE TITLE
Demo wont work

### ISSUE THREAD

**Issue by pawisoon** [nomasters/killcord#20]
When running commands from https://killcord.io/ 

`killcord decrypt` returns 

`no killcord.toml found, run killcord init to start a new project`

Platform MacOS 13.4.1 (22F82)

**Comment by n2p5** [comment]
Oh, good catch! This was using infra and a free public API key, which they no longer support. so the demo is currently broken. I haven't looked at this project in a long time, so I'll brush up on it this week and see what's going on and if there is an easy fix. 

I appreciate the bug report.

**Comment by pawisoon** [comment]
No problem! Thanks for addressing the problem. I wish I could do a PR with a fix to speed it up ;)
