### ISSUE TITLE
Include support for HTTP proxy

### ISSUE THREAD

**Issue by weltonrodrigo** [nomasters/killcord#5]
When run over a proxy, `killcord watch` will timeout.

`
adding payload endpoint to project configuration
adding decryption key to project configuration
decrypt the payload by running: killcord decrypt
Post https://ipfs.infura.io:5001/api/v0/get?arg=Qmf5UHYAiwZ1A95MkkyEEbhGDErA5dLWcG7zYR6A5Aq3fG&encoding=json&stream-channels=true&: dial tcp 34.192.181.130:5001: connect: connection timed out
`

**Comment by n2p5** [comment]
Oh interesting. I'll look into this.
